
kind: CSIDriver
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: efs.csi.aws.com
spec:
  attachRequired: false
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-solr-sc
provisioner: efs.csi.aws.com
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-zookeeper-sc
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: $SOLR_ENV-solr1-efs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-solr-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: $SOLR1_EFS_FS_ID::$SOLR1_EFS_AP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: $SOLR_ENV-solr2-efs-pv
  namespace: $SOLR_ENV
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-solr-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: $SOLR2_EFS_FS_ID::$SOLR2_EFS_AP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: $SOLR_ENV-solr3-efs-pv
  namespace: $SOLR_ENV
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-solr-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: $SOLR3_EFS_FS_ID::$SOLR3_EFS_AP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: $SOLR_ENV-zookeeper1-efs-pv
  namespace: $SOLR_ENV
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-zookeeper-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: $ZOOKEEPER1_EFS_FS_ID::$ZOOKEEPER1_EFS_AP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: $SOLR_ENV-zookeeper2-efs-pv
  namespace: $SOLR_ENV
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-zookeeper-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: $ZOOKEEPER2_EFS_FS_ID::$ZOOKEEPER2_EFS_AP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: $SOLR_ENV-zookeeper3-efs-pv
  namespace: $SOLR_ENV
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-zookeeper-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: $ZOOKEEPER3_EFS_FS_ID::$ZOOKEEPER3_EFS_AP
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-solr-backup-sc
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: $SOLR_ENV-solr-backup-efs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-solr-backup-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: $SOLR_BACKUP_EFS_FS_ID::$SOLR_BACKUP_EFS_AP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solr-backup-efs-pvc
  namespace: $SOLR_ENV
spec:
  storageClassName: efs-solr-backup-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
