apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: solr
    app.kubernetes.io/instance: solr
    app.kubernetes.io/name: solr
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: solr
      app.kubernetes.io/instance: solr
      app.kubernetes.io/name: solr
  template:
    metadata:
      labels:
        app.kubernetes.io/component: solr
        app.kubernetes.io/instance: solr
        app.kubernetes.io/name: solr
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - name: solr-client
          containerPort: 8983
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -ec
              - |
                sed -i 's/80/8983/g' /etc/nginx/conf.d/default.conf
                sed -i 's/location \//location \/solr { return 200 "Search will be back shortly"; add_header Content-Type text\/plain; } location \//' /etc/nginx/conf.d/default.conf
                service nginx reload
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi